[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lf17_sensor"
dynamic = ["version"]
dependencies = [
    "PySide6",
]

[project.optional-dependencies]
dev = [
    "black",
    "mypy",
]

[tool.setuptools.packages.find]
where = ["src"]
