site_name: LF17 Docs
theme:
  name: material
nav:
  - "00: Start": index.md
  - "01: Wdh. Klassenbeziehungen": 01_klassenbeziehungen.md
  - "02: IT-Sicherheit": 02_it-sicherheit.md
  - "03: Datenschutz": 03_datenschutz.md
  - "04: Software-Architekturmodelle": 04_software-architecture.md
  - "05: Begriffe zur Projektierung": 05_projektierung.md
  - "Aufgaben":
    - "01: Klassenbeziehungen": 01_klassenbeziehungen-aufgaben.md
    - "01: Klassenbeziehungen Lösungen": 01_klassenbeziehungen-aufgaben-loesung.md
    - "01: Abstrakte Klassen": 01_aufgabe-2.3.md
    - "02: IT-Sicherheit": 02_it-sicherheit-aufgaben.md
    - "03: Datenschutz": 03_datenschutz-aufgaben.md
    - "04: Softwareprototyp": 04_aufgabe-2.1.md
    - "05: Klassendiagram": 05_aufgabe-2.2.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
