site_name: LF17 Docs
theme:
  name: material
nav:
  - Home: index.md
  - Aufgabe Softwareprototyp: aufgabe-2.1.md
  - Aufgabe Abstrakte Klassen: aufgabe-2.3.md
  - Aufgaben Klassenbeziehungen: klassenbeziehungen-aufgaben.md
  - Aufgaben Klassenbeziehungen Lösungen: klassenbeziehungen-aufgaben-loesung.md
  - Wdh. Klassenbeziehungen: klassenbeziehungen.md
  - Wdh. MVC: mvc.md
  - IT-Sicherheit: it-sicherheit.md
  - Datenschutz: datenschutz.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
