site_name: LF17 Docs
theme:
  name: material
nav:
  - Home: index.md
  - Wdh. Klassenbeziehungen: klassenbeziehungen.md
  - Wdh. MVC: mvc.md
  - Wdh. IT-Sicherheit: it-sicherheit.md
  - Wdh. Datenschutz: datenschutz.md
  - Aufgaben:
    - Softwareprototyp: aufgabe-2.1.md
    - Abstrakte Klassen: aufgabe-2.3.md
    - Klassenbeziehungen: klassenbeziehungen-aufgaben.md
    - Klassenbeziehungen Lösungen: klassenbeziehungen-aufgaben-loesung.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
